# Add two game-owned entry hooks to generated copies. Keep the upstream
# framework and original generated files intact; fail if the emitter changes.
foreach(_pair "00|8001270C|shinka_journal_quick_menu" "02|80016B88|shinka_journal_transition")
    string(REPLACE "|" ";" _fields "${_pair}")
    list(GET _fields 0 _shard)
    list(GET _fields 1 _address)
    list(GET _fields 2 _callback)
    set(_original "${CMAKE_CURRENT_SOURCE_DIR}/output/recompiled/SLES_039.36_full_${_shard}.c")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_original}")
    file(READ "${_original}" _code)
    set(_needle "debug_server_log_call_entry(0x${_address}u);")
    string(REGEX MATCHALL "${_callback}\\(cpu\\)" _already "${_code}")
    string(FIND "${_code}" "${_needle}" _found)
    # Each hook belongs to one real function entry, not an overlapping alias.
    string(REPLACE "${_needle}" "" _without "${_code}")
    string(LENGTH "${_code}" _before_length)
    string(LENGTH "${_without}" _after_length)
    string(LENGTH "${_needle}" _needle_length)
    math(EXPR _removed "${_before_length} - ${_after_length}")
    if(_found EQUAL -1 OR _already OR NOT _removed EQUAL _needle_length)
        message(FATAL_ERROR "Review the generated journal hook at ${_address}")
    endif()
    string(REPLACE "${_needle}" "${_needle}\n    ${_callback}(cpu);" _code "${_code}")
    string(REPLACE "#include \"SLES_039.36_decls.h\""
        "#include \"SLES_039.36_decls.h\"\nextern void ${_callback}(CPUState* cpu);" _code "${_code}")
    set(_copy "${CMAKE_CURRENT_BINARY_DIR}/shinka-runtime/journal_${_shard}.c")
    file(CONFIGURE OUTPUT "${_copy}" CONTENT "${_code}" @ONLY)
    get_target_property(_sources shinka SOURCES)
    if(NOT "${_original}" IN_LIST _sources)
        message(FATAL_ERROR "Generated game source layout changed: ${_original}")
    endif()
    list(REMOVE_ITEM _sources "${_original}")
    set_property(TARGET shinka PROPERTY SOURCES "${_sources}")
    target_sources(shinka PRIVATE "${_copy}")
endforeach()
target_sources(shinka PRIVATE src/journal_menu.c)
target_include_directories(shinka PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/output/recompiled")
