# Low-overhead movie timing diagnostics; the pinned framework stays untouched.
set(_movie_debug "${_generated}/debug_server.c")
file(READ "${_movie_debug}" _movie_debug_text)
# The old 16 KiB response silently kept only ~120 rows. A whole-ring snapshot
# avoids polling the game during measurements (4096 frames, ~82 seconds PAL).
set(_old "        static char rawbuf[16384];\n        latency_ring_dump_json(rawbuf, sizeof(rawbuf), count);")
string(FIND "${_movie_debug_text}" "${_old}" _pos)
if(_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned latency response capacity")
endif()
string(REPLACE "${_old}" "        static char rawbuf[1024 * 1024];\n        if (count < 1) count = 120;\n        if (count > 4096) count = 4096;\n        latency_ring_dump_json(rawbuf, sizeof(rawbuf), count);" _movie_debug_text "${_movie_debug_text}")
file(CONFIGURE OUTPUT "${_movie_debug}" CONTENT "${_movie_debug_text}" @ONLY)
# Preserve the callback-entry timestamp before the input-latency path restamps
# it after sleeping. This separates guest work from pacing in an offline dump.
set(_original "${PSXRECOMP_ROOT}/runtime/src/latency_ring.c")
file(READ "${_original}" _latency)
foreach(_anchor "    uint64_t frame;" "    s->ts[LAT_INPUT] = qpc();" "base = s->ts[LAT_INPUT]" "(unsigned long long)s->frame, ti, tp")
    string(FIND "${_latency}" "${_anchor}" _pos)
    if(_pos EQUAL -1)
        message(FATAL_ERROR "Review pinned latency ring anchor: ${_anchor}")
    endif()
endforeach()
set(_old "    uint64_t frame;")
set(_new "    uint64_t frame;\n    uint64_t begin;")
string(REPLACE "${_old}" "${_new}" _latency "${_latency}")
string(REPLACE "    s->ts[LAT_INPUT] = qpc();" "    s->ts[LAT_INPUT] = qpc();\n    s->begin = s->ts[LAT_INPUT];" _latency "${_latency}")
string(REPLACE "base = s->ts[LAT_INPUT]" "base = s->begin" _latency "${_latency}")
set(_old [=[\"input\":%.1f,\"paced\":%.1f]=])
string(FIND "${_latency}" "${_old}" _pos)
if(_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned latency timestamp serialization")
endif()
string(REPLACE "${_old}" [=[\"begin\":%.1f,\"input\":%.1f,\"paced\":%.1f]=] _latency "${_latency}")
string(REPLACE "(unsigned long long)s->frame, ti, tp" "(unsigned long long)s->frame, (double)(s->begin - base) * inv_us, ti, tp" _latency "${_latency}")
file(CONFIGURE OUTPUT "${_generated}/latency_ring.c" CONTENT "${_latency}" @ONLY)
get_target_property(_sources shinka SOURCES)
if(NOT "${_original}" IN_LIST _sources)
    message(FATAL_ERROR "Review latency source ownership")
endif()
list(REMOVE_ITEM _sources "${_original}")
list(APPEND _sources "${_generated}/latency_ring.c")
set_property(TARGET shinka PROPERTY SOURCES "${_sources}")
if(SHINKA_BUILD_TESTS)
    string(REPLACE "#include \"psx_sdl.h\""
        "extern uint64_t SDL_GetPerformanceCounter(void);\nextern uint64_t SDL_GetPerformanceFrequency(void);" _latency_test "${_latency}")
    file(CONFIGURE OUTPUT "${_generated}/latency_ring_test.c" CONTENT "${_latency_test}" @ONLY)
    add_executable(shinka_movie_latency_test tests/test_movie_latency.c "${_generated}/latency_ring_test.c")
    target_include_directories(shinka_movie_latency_test PRIVATE "${PSXRECOMP_ROOT}/runtime/include")
    add_test(NAME movie_latency COMMAND shinka_movie_latency_test)
endif()
