set(_view_gte "${PSXRECOMP_ROOT}/runtime/src/gte.cpp")
file(READ "${_view_gte}" _view_code)
set(_view_old "    int64_t sx16 = gte->OFX + xterm;\n    int64_t sy16 = gte->OFY + (int64_t)gte->IR2 * h_div_sz;")
string(FIND "${_view_code}" "${_view_old}" _view_pos)
if(_view_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned GTE projection for battle zoom")
endif()
string(REPLACE "${_view_old}"
    "    int64_t yterm = (int64_t)gte->IR2 * h_div_sz;\n    shinka_view_project(&xterm, &yterm);\n    int64_t sx16 = gte->OFX + xterm;\n    int64_t sy16 = gte->OFY + yterm;"
    _view_code "${_view_code}")
file(CONFIGURE OUTPUT "${_generated}/gte.cpp" CONTENT "#include \"view.h\"\n${_view_code}" @ONLY)
get_target_property(_view_sources shinka SOURCES)
if(NOT "${_view_gte}" IN_LIST _view_sources)
    message(FATAL_ERROR "Review pinned GTE source target")
endif()
list(REMOVE_ITEM _view_sources "${_view_gte}")
list(APPEND _view_sources "${_generated}/gte.cpp")
set_property(TARGET shinka PROPERTY SOURCES "${_view_sources}")
target_sources(shinka PRIVATE src/view.c)
set(_hud_gpu "${PSXRECOMP_ROOT}/runtime/src/gpu.c")
file(READ "${_hud_gpu}" _hud_code)
set(_hud_anchor "    gp0_ring_record(gp0_cmd_buf, gp0_words_needed);")
string(REPLACE "${_hud_anchor}" "${_hud_anchor}\n    shinka_field_gpu_source(gp0_cmd_source_addr);" _hud_code "${_hud_code}")
string(FIND "${_hud_code}" "${_hud_anchor}" _hud_pos)
if(_hud_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned GPU command collection for battle HUD")
endif()
string(REPLACE "${_hud_anchor}"
    "${_hud_anchor}\n    int dialogue_x = 0;\n    shinka_hud_dialogue_width = shinka_battle_dialogue_tile(gp0_cmd_buf, gp0_words_needed, draw_offset_x, draw_offset_y,\n        draw_area_left, draw_area_top, draw_area_right, draw_area_bottom, ws_nw_extra()/2, &dialogue_x);\n    shinka_battle_hud_command(gp0_cmd_buf, gp0_words_needed, draw_offset_x, draw_offset_y,\n        draw_area_left, draw_area_top, draw_area_right, draw_area_bottom, ws_nw_extra()/2);\n    if (shinka_hud_dialogue_width) gp0_cmd_buf[1] = (gp0_cmd_buf[1]&0xffff0000u)|(uint16_t)dialogue_x;"
    _hud_code "${_hud_code}")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/src/battle_hud_gpu.inc" _hud_helpers)
set(_hud_copy "            gr_copy_rect(src_x, src_y, dst_x, dst_y, w, h);")
set(_hud_target "    gr_wide_configure(ws_nw_present_width(), ws_nw_offset());")
foreach(_anchor "${_hud_copy}" "${_hud_target}" "static void gp0_execute_command(void) {")
    string(FIND "${_hud_code}" "${_anchor}" _pos)
    if(_pos EQUAL -1)
        message(FATAL_ERROR "Review pinned battle HUD cursor/portrait integration")
    endif()
endforeach()
string(REPLACE "${_hud_copy}" "            if (!shinka_hud_cursor_blit(src_x, src_y, dst_x, dst_y, w, h))\n    ${_hud_copy}" _hud_code "${_hud_code}")
string(REPLACE "${_hud_target}"
    "${_hud_target}\n    if (shinka_battle_hud_portrait(draw_area_left,draw_area_top,draw_area_right,draw_area_bottom,ws_nw_extra()/2)) {\n        gr_wide_set_target(0); return;\n    }"
    _hud_code "${_hud_code}")
string(REPLACE "static void gp0_execute_command(void) {" "${_hud_helpers}\nstatic void gp0_execute_command(void) {" _hud_code "${_hud_code}")
set(_hud_stretch "    int ws_w = 0;\n    if (ws_active() && w > 0) {")
string(FIND "${_hud_code}" "${_hud_stretch}" _hud_stretch_pos)
if(_hud_stretch_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned textured rectangle stretch path")
endif()
string(REPLACE "${_hud_stretch}" "    int ws_w = shinka_hud_dialogue_width;\n    if (ws_active() && w > 0) {" _hud_code "${_hud_code}")
set(_menu_anchor "    if (shinka_hud_dialogue_width) gp0_cmd_buf[1] = (gp0_cmd_buf[1]&0xffff0000u)|(uint16_t)dialogue_x;")
string(REPLACE "${_menu_anchor}" "${_menu_anchor}\n    if (!shinka_hud_dialogue_width) shinka_hud_dialogue_width = shinka_menu_wide_rect(\n        gp0_cmd_buf, gp0_words_needed, draw_offset_x, draw_offset_y,\n        draw_area_left, draw_area_top, draw_area_right, draw_area_bottom, ws_nw_extra()/2);" _hud_code "${_hud_code}")
file(CONFIGURE OUTPUT "${_generated}/gpu.c" CONTENT "#include \"battle_hud.h\"\n#include \"menu_wide.h\"\n#include \"field_tiles.h\"\nstatic int shinka_hud_dialogue_width;\n${_hud_code}" @ONLY)
get_target_property(_hud_sources shinka SOURCES)
if(NOT "${_hud_gpu}" IN_LIST _hud_sources)
    message(FATAL_ERROR "Review pinned GPU source target")
endif()
list(REMOVE_ITEM _hud_sources "${_hud_gpu}")
list(APPEND _hud_sources "${_generated}/gpu.c")
set_property(TARGET shinka PROPERTY SOURCES "${_hud_sources}")
set(_hud_gl "${PSXRECOMP_ROOT}/runtime/src/gpu_gl_renderer.c")
file(READ "${_hud_gl}" _hud_gl_code)
# Record the actual GL device, not merely the configured backend. Hybrid laptops
# can select either adapter even when both advertise the same driver version.
set(_gl_identity "    const char *ver = (const char *)glGetString(GL_VERSION);")
string(FIND "${_hud_gl_code}" "${_gl_identity}" _gl_identity_pos)
if(_gl_identity_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned GL context device diagnostics")
endif()
string(REPLACE "${_gl_identity}"
    "${_gl_identity}\n    const char *vendor = (const char *)glGetString(GL_VENDOR);\n    const char *device = (const char *)glGetString(GL_RENDERER);\n    fprintf(stdout, \"Shinka graphics: vendor=%s; device=%s\\n\", vendor ? vendor : \"?\", device ? device : \"?\");"
    _hud_gl_code "${_hud_gl_code}")
set(_hud_scissor "        glScissor(0, sy * s_scale, g_wide_w * s_scale, sh * s_scale);")
string(FIND "${_hud_gl_code}" "${_hud_scissor}" _hud_scissor_pos)
if(_hud_scissor_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned native-wide portrait clipping")
endif()
string(REPLACE "${_hud_scissor}"
    "        if (shinka_battle_hud_portrait(s_area_x1,s_area_y1,s_area_x2,s_area_y2,g_wide_off))\n            glScissor((s_area_x1+dx)*s_scale,sy*s_scale,(s_area_x2-s_area_x1+1)*s_scale,sh*s_scale);\n        else\n${_hud_scissor}"
    _hud_gl_code "${_hud_gl_code}")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/src/field_tiles_gl.inc" _field_gl)
set(_field_rect "static void glb_draw_textured_rect(int x,int y,int w,int h,int u,int v,uint16_t cx,uint16_t cy,uint16_t tp){")
set(_field_batch "    hr_begin(1);\n    p_glUseProgram(s_tex_prog);\n    p_glActiveTexture(PSXGL_TEXTURE0);\n    glBindTexture(GL_TEXTURE_2D, s_raw_tex);")
set(_field_backend "/* ---- backend vtable wrappers ------------------------------------------- */")
foreach(_anchor "${_field_rect}" "${_field_batch}" "${_field_backend}" "void gl_renderer_shutdown(void) {")
    string(FIND "${_hud_gl_code}" "${_anchor}" _pos)
    if(_pos EQUAL -1)
        message(FATAL_ERROR "Review private field texture integration")
    endif()
endforeach()
string(REPLACE "${_field_backend}" "${_field_gl}\n${_field_backend}" _hud_gl_code "${_hud_gl_code}")
string(REPLACE "${_field_rect}" "${_field_rect}\n    if (shinka_field_gl_rect(x,y,w,h,u,v)) return;" _hud_gl_code "${_hud_gl_code}")
string(REPLACE "${_field_batch}" "    hr_begin(1);\n    p_glUseProgram(s_tex_prog);\n    p_glActiveTexture(PSXGL_TEXTURE0);\n    glBindTexture(GL_TEXTURE_2D, shinka_field_raw_texture ? shinka_field_raw_texture : s_raw_tex);" _hud_gl_code "${_hud_gl_code}")
string(REPLACE "void gl_renderer_shutdown(void) {" "void gl_renderer_shutdown(void) {\n    flush_tex_batch();\n    shinka_field_gl_reset();" _hud_gl_code "${_hud_gl_code}")
file(CONFIGURE OUTPUT "${_generated}/gpu_gl_renderer.c" CONTENT "#include \"battle_hud.h\"\n#include \"field_tiles.h\"\nstatic unsigned int shinka_field_raw_texture;\n${_hud_gl_code}" @ONLY)
get_target_property(_hud_sources shinka SOURCES)
if(NOT "${_hud_gl}" IN_LIST _hud_sources)
    message(FATAL_ERROR "Review pinned GL source target")
endif()
list(REMOVE_ITEM _hud_sources "${_hud_gl}")
list(APPEND _hud_sources "${_generated}/gpu_gl_renderer.c")
set_property(TARGET shinka PROPERTY SOURCES "${_hud_sources}")
target_sources(shinka PRIVATE src/battle_hud.c src/menu_wide.c)
target_sources(shinka PRIVATE src/field_tiles.c src/field_tile_decode.c)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/field_tiles_gl.inc")
target_include_directories(shinka PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_view_gte}" "${_hud_gpu}" "${_hud_gl}" "${CMAKE_CURRENT_SOURCE_DIR}/src/battle_hud_gpu.inc")
if(SHINKA_BUILD_TESTS)
    add_executable(shinka_field_tiles_test tests/test_field_tiles.c src/field_tiles.c src/field_tile_decode.c)
    target_include_directories(shinka_field_tiles_test PRIVATE src "${PSXRECOMP_ROOT}/runtime/include")
    add_test(NAME field_tiles COMMAND shinka_field_tiles_test)
    add_executable(shinka_view_test tests/test_view.c src/view.c src/battle_hud.c src/menu_wide.c)
    target_include_directories(shinka_view_test PRIVATE src "${PSXRECOMP_ROOT}/runtime/include")
    add_test(NAME view COMMAND shinka_view_test)
endif()
