set(_view_gte "${PSXRECOMP_ROOT}/runtime/src/gte.cpp")
file(READ "${_view_gte}" _view_code)
set(_view_old "    int64_t sx16 = gte->OFX + xterm;\n    int64_t sy16 = gte->OFY + (int64_t)gte->IR2 * h_div_sz;")
string(FIND "${_view_code}" "${_view_old}" _view_pos)
if(_view_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned GTE projection for battle zoom")
endif()
string(REPLACE "${_view_old}"
    "    int64_t yterm = (int64_t)gte->IR2 * h_div_sz;\n    shinka_view_project(&xterm, &yterm);\n    int64_t sx16 = gte->OFX + xterm;\n    int64_t sy16 = gte->OFY + yterm;"
    _view_code "${_view_code}")
file(CONFIGURE OUTPUT "${_generated}/gte.cpp" CONTENT "#include \"view.h\"\n${_view_code}" @ONLY)
get_target_property(_view_sources shinka SOURCES)
if(NOT "${_view_gte}" IN_LIST _view_sources)
    message(FATAL_ERROR "Review pinned GTE source target")
endif()
list(REMOVE_ITEM _view_sources "${_view_gte}")
list(APPEND _view_sources "${_generated}/gte.cpp")
set_property(TARGET shinka PROPERTY SOURCES "${_view_sources}")
target_sources(shinka PRIVATE src/view.c)
set(_hud_gpu "${PSXRECOMP_ROOT}/runtime/src/gpu.c")
file(READ "${_hud_gpu}" _hud_code)
set(_hud_anchor "    gp0_ring_record(gp0_cmd_buf, gp0_words_needed);")
string(FIND "${_hud_code}" "${_hud_anchor}" _hud_pos)
if(_hud_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned GPU command collection for battle HUD")
endif()
string(REPLACE "${_hud_anchor}"
    "${_hud_anchor}\n    shinka_battle_hud_command(gp0_cmd_buf, gp0_words_needed, draw_offset_x, draw_offset_y,\n        draw_area_left, draw_area_top, draw_area_right, draw_area_bottom, ws_nw_extra()/2);"
    _hud_code "${_hud_code}")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/src/battle_hud_gpu.inc" _hud_helpers)
set(_hud_copy "            gr_copy_rect(src_x, src_y, dst_x, dst_y, w, h);")
set(_hud_target "    gr_wide_configure(ws_nw_present_width(), ws_nw_offset());")
foreach(_anchor "${_hud_copy}" "${_hud_target}" "static void gp0_execute_command(void) {")
    string(FIND "${_hud_code}" "${_anchor}" _pos)
    if(_pos EQUAL -1)
        message(FATAL_ERROR "Review pinned battle HUD cursor/portrait integration")
    endif()
endforeach()
string(REPLACE "${_hud_copy}" "            if (!shinka_hud_cursor_blit(src_x, src_y, dst_x, dst_y, w, h))\n    ${_hud_copy}" _hud_code "${_hud_code}")
string(REPLACE "${_hud_target}"
    "${_hud_target}\n    if (shinka_battle_hud_portrait(draw_area_left,draw_area_top,draw_area_right,draw_area_bottom,ws_nw_extra()/2)) {\n        gr_wide_set_target(0); return;\n    }"
    _hud_code "${_hud_code}")
string(REPLACE "static void gp0_execute_command(void) {" "${_hud_helpers}\nstatic void gp0_execute_command(void) {" _hud_code "${_hud_code}")
file(CONFIGURE OUTPUT "${_generated}/gpu.c" CONTENT "#include \"battle_hud.h\"\n${_hud_code}" @ONLY)
get_target_property(_hud_sources shinka SOURCES)
if(NOT "${_hud_gpu}" IN_LIST _hud_sources)
    message(FATAL_ERROR "Review pinned GPU source target")
endif()
list(REMOVE_ITEM _hud_sources "${_hud_gpu}")
list(APPEND _hud_sources "${_generated}/gpu.c")
set_property(TARGET shinka PROPERTY SOURCES "${_hud_sources}")
set(_hud_gl "${PSXRECOMP_ROOT}/runtime/src/gpu_gl_renderer.c")
file(READ "${_hud_gl}" _hud_gl_code)
set(_hud_scissor "        glScissor(0, sy * s_scale, g_wide_w * s_scale, sh * s_scale);")
string(FIND "${_hud_gl_code}" "${_hud_scissor}" _hud_scissor_pos)
if(_hud_scissor_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned native-wide portrait clipping")
endif()
string(REPLACE "${_hud_scissor}"
    "        if (shinka_battle_hud_portrait(s_area_x1,s_area_y1,s_area_x2,s_area_y2,g_wide_off))\n            glScissor((s_area_x1+dx)*s_scale,sy*s_scale,(s_area_x2-s_area_x1+1)*s_scale,sh*s_scale);\n        else\n${_hud_scissor}"
    _hud_gl_code "${_hud_gl_code}")
file(CONFIGURE OUTPUT "${_generated}/gpu_gl_renderer.c" CONTENT "#include \"battle_hud.h\"\n${_hud_gl_code}" @ONLY)
get_target_property(_hud_sources shinka SOURCES)
if(NOT "${_hud_gl}" IN_LIST _hud_sources)
    message(FATAL_ERROR "Review pinned GL source target")
endif()
list(REMOVE_ITEM _hud_sources "${_hud_gl}")
list(APPEND _hud_sources "${_generated}/gpu_gl_renderer.c")
set_property(TARGET shinka PROPERTY SOURCES "${_hud_sources}")
target_sources(shinka PRIVATE src/battle_hud.c)
target_include_directories(shinka PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_view_gte}" "${_hud_gpu}" "${_hud_gl}" "${CMAKE_CURRENT_SOURCE_DIR}/src/battle_hud_gpu.inc")
if(SHINKA_BUILD_TESTS)
    add_executable(shinka_view_test tests/test_view.c src/view.c src/battle_hud.c)
    target_include_directories(shinka_view_test PRIVATE src "${PSXRECOMP_ROOT}/runtime/include")
    add_test(NAME view COMMAND shinka_view_test)
endif()
