set(_view_gte "${PSXRECOMP_ROOT}/runtime/src/gte.cpp")
file(READ "${_view_gte}" _view_code)
set(_view_old "    int64_t sx16 = gte->OFX + xterm;\n    int64_t sy16 = gte->OFY + (int64_t)gte->IR2 * h_div_sz;")
string(FIND "${_view_code}" "${_view_old}" _view_pos)
if(_view_pos EQUAL -1)
    message(FATAL_ERROR "Review pinned GTE projection for battle zoom")
endif()
string(REPLACE "${_view_old}"
    "    int64_t yterm = (int64_t)gte->IR2 * h_div_sz;\n    shinka_view_project(&xterm, &yterm);\n    int64_t sx16 = gte->OFX + xterm;\n    int64_t sy16 = gte->OFY + yterm;"
    _view_code "${_view_code}")
file(CONFIGURE OUTPUT "${_generated}/gte.cpp" CONTENT "#include \"view.h\"\n${_view_code}" @ONLY)
get_target_property(_view_sources shinka SOURCES)
if(NOT "${_view_gte}" IN_LIST _view_sources)
    message(FATAL_ERROR "Review pinned GTE source target")
endif()
list(REMOVE_ITEM _view_sources "${_view_gte}")
list(APPEND _view_sources "${_generated}/gte.cpp")
set_property(TARGET shinka PROPERTY SOURCES "${_view_sources}")
target_sources(shinka PRIVATE src/view.c)
target_include_directories(shinka PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_view_gte}")
if(SHINKA_BUILD_TESTS)
    add_executable(shinka_view_test tests/test_view.c src/view.c)
    target_include_directories(shinka_view_test PRIVATE src "${PSXRECOMP_ROOT}/runtime/include")
    add_test(NAME view COMMAND shinka_view_test)
endif()
